server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.cpuvzwftvmcz.ap-northeast-2.rds.amazonaws.com:3306/teamproject-lash-20221104?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

  security:
    user:
      name: admin
      password: 1q2w3e4r
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 68895121061-5o8mgm75kafj2eu84j1e8mh6q6nqhsvv.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - email
#              - profile
#          naver:
#            clientId: kNi4Fzaf0uc0R8ya5qmg
#            clientSecret: bwFzkipLvV
#            scope:
#              - email
#              - name
#            clientName: Naver
#            authorizationGrantType: authorization_code
#            redirectUri: http://localhost:8000/login/oauth2/code/naver
#        provider:
#          naver:
#            authorizationUri: https://nid.naver.com/oauth2.0/authorize
#            tokenUri: https://nid.naver.com/oauth2.0/token
#            userInfoUri: https://openapi.naver.com/v1/nid/me
#            userNameAttribute: response

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/TeamProjectLash/web/springboot/teamproject-lash-clone-20221104/upload/